-- ShopFlow schema. The lab's V1 single-table order model is replaced (lab data only, nothing to migrate).
DROP TABLE IF EXISTS purchase_order;

CREATE TABLE customer (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    name       VARCHAR(255) NOT NULL,
    tier       VARCHAR(16)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE product (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         VARCHAR(32)    NOT NULL UNIQUE,
    name        VARCHAR(255)   NOT NULL,
    category    VARCHAR(64)    NOT NULL,
    price       NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    description VARCHAR(2000)
);
CREATE INDEX idx_product_category_name ON product (category, name);

-- Stock is changed only with atomic conditional updates (see InventoryRepository)
CREATE TABLE inventory (
    product_id BIGINT PRIMARY KEY REFERENCES product (id),
    available  INT NOT NULL CHECK (available >= 0)
);

CREATE TABLE purchase_order (
    id           UUID PRIMARY KEY,
    customer_id  BIGINT         NOT NULL REFERENCES customer (id),
    status       VARCHAR(16)    NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    payment_id   UUID,
    created_at   TIMESTAMPTZ    NOT NULL,
    version      BIGINT         NOT NULL
);
-- Customer order history (newest first) and date-range reports
CREATE INDEX idx_order_customer_created ON purchase_order (customer_id, created_at DESC);
CREATE INDEX idx_order_created ON purchase_order (created_at);

-- Sequence with increment 50 matches Hibernate's allocationSize, so line inserts can be JDBC-batched
CREATE SEQUENCE order_line_seq INCREMENT BY 50;
CREATE TABLE order_line (
    id         BIGINT PRIMARY KEY DEFAULT nextval('order_line_seq'),
    order_id   UUID           NOT NULL REFERENCES purchase_order (id),
    product_id BIGINT         NOT NULL REFERENCES product (id),
    quantity   INT            NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL
);
CREATE INDEX idx_order_line_order ON order_line (order_id);
CREATE INDEX idx_order_line_product ON order_line (product_id);
